version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - stable-finance-app

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - stable-finance-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8000:80"
    environment:
      PMA_ABSOLUTE_URI: http://localhost:8000/
      PMA_HOST: mysql # Connect database host
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 200M
      MAX_EXECUTION_TIME: 300
    depends_on:
      - mysql
    networks:
      - stable-finance-app

networks:
  stable-finance-app:
    driver: bridge

volumes:
  mysql_data: