<?php
const TRANSACTION_TYPE_INCOME = "Income";
const TRANSACTION_TYPE_BUDGET = "Budget";
const TRANSACTION_TYPE_SAVING = "Saving";
const TRANSACTION_TYPE_DEBT = "Debt";

const TRANSACTION_TYPE_EXPENSE_OPTION = [
    TRANSACTION_TYPE_BUDGET,
    TRANSACTION_TYPE_SAVING,
    TRANSACTION_TYPE_DEBT
]
?>